name: build site from templates & data

on:
  push:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.5.2]

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno run --allow-read --allow-write --allow-net gen.js
      - uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: regenerate site
          branch: ${{ github.head_ref }}
